### ISSUE TITLE
/snpc list not working

### ISSUE THREAD

**Issue by TheMicCraft** [brokiem/SimpleNPC#95]
**Describe the bug**
After updating to version 4.0.0-beta, there are no NPCs displayed at /snpc list, although there are multiple (human) NPCs in this world and they work normally. Newly created NPCs are also not displayed. Restarting the server does not help either.

**To Reproduce**
1. Spawn a NPC with "/snpc spawn ..."
2. Enter command "/snpc list"

**Screenshots**
![image](https://user-images.githubusercontent.com/101190520/184175357-01844b62-2583-4c6b-adb5-dd74c1b90dea.png)

**SimpleNPC plugin information**
- Version: 4.0.0-beta
- Server API: 4.7.0

**Comment by brokiem** [comment]
Should be fixed in v4.0.1

**Comment by TheMicCraft** [comment]
![image](https://user-images.githubusercontent.com/101190520/205438089-8e61c819-1272-4efb-b4bc-a48f052aacc4.png)
It still doesn't work quite right. Only with the UI you can let it print the locations in the chat.
